package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/unxed/libwinescape/spec"
)

func generateGoFile(targetOS spec.TargetOS, targetArch spec.TargetArch) string {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-numbers. DO NOT EDIT.\n\n")
	buf.WriteString("package winescape\n\n")
	buf.WriteString("const (\n")

	for _, entry := range spec.SyscallTable {
		if osMap, ok := entry.Numbers[targetOS]; ok {
			if num, ok := osMap[targetArch]; ok {
				constName := fmt.Sprintf("sys%s", strings.ToUpper(entry.Name[:1])+entry.Name[1:])
				buf.WriteString(fmt.Sprintf("\t%s uintptr = %d\n", constName, num))
			}
		}
	}

	buf.WriteString(")\n")
	return buf.String()
}

func generateCHeader() string {
	var buf bytes.Buffer
	buf.WriteString("/* Code generated by cmd/gen-numbers. DO NOT EDIT. */\n")
	buf.WriteString("#ifndef WINESCAPE_NUMBERS_H\n")
	buf.WriteString("#define WINESCAPE_NUMBERS_H\n\n")

	targets := []struct {
		os   spec.TargetOS
		arch spec.TargetArch
		cond string
	}{
		{spec.OSLinux, spec.ArchAMD64, "defined(__linux__) && (defined(__x86_64__) || defined(_M_X64))"},
		{spec.OSLinux, spec.ArchARM64, "defined(__linux__) && (defined(__aarch64__) || defined(_M_ARM64))"},
		{spec.OSFreeBSD, spec.ArchAMD64, "defined(__FreeBSD__) && (defined(__x86_64__) || defined(_M_X64))"},
	}

	for i, t := range targets {
		if i == 0 {
			buf.WriteString(fmt.Sprintf("#if %s\n", t.cond))
		} else {
			buf.WriteString(fmt.Sprintf("#elif %s\n", t.cond))
		}

		for _, entry := range spec.SyscallTable {
			if osMap, ok := entry.Numbers[t.os]; ok {
				if num, ok := osMap[t.arch]; ok {
					macroName := fmt.Sprintf("WS_SYS_%s", strings.ToUpper(entry.Name))
					buf.WriteString(fmt.Sprintf("#define %s %d\n", macroName, num))
				}
			}
		}
	}

	buf.WriteString("#else\n")
	buf.WriteString("#error \"Unsupported host OS / architecture combination for libwinescape\"\n")
	buf.WriteString("#endif\n\n")
	buf.WriteString("#endif /* WINESCAPE_NUMBERS_H */\n")

	return buf.String()
}

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	goFiles := []struct {
		os   spec.TargetOS
		arch spec.TargetArch
		path string
	}{
		{spec.OSLinux, spec.ArchAMD64, filepath.Join(rootDir, "go", "numbers_linux_amd64.go")},
		{spec.OSLinux, spec.ArchARM64, filepath.Join(rootDir, "go", "numbers_linux_arm64.go")},
		{spec.OSFreeBSD, spec.ArchAMD64, filepath.Join(rootDir, "go", "numbers_freebsd_amd64.go")},
	}

	for _, gf := range goFiles {
		content := generateGoFile(gf.os, gf.arch)
		if err := os.MkdirAll(filepath.Dir(gf.path), 0755); err != nil {
			fmt.Fprintf(stderr(), "mkdir error: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(gf.path, []byte(content), 0644); err != nil {
			fmt.Fprintf(stderr(), "write error for %s: %v\n", gf.path, err)
			os.Exit(1)
		}
		fmt.Printf("Generated %s\n", gf.path)
	}

	cHeaderPath := filepath.Join(rootDir, "c", "include", "winescape_numbers.h")
	if err := os.MkdirAll(filepath.Dir(cHeaderPath), 0755); err != nil {
		fmt.Fprintf(stderr(), "mkdir error: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(cHeaderPath, []byte(generateCHeader()), 0644); err != nil {
		fmt.Fprintf(stderr(), "write error for %s: %v\n", cHeaderPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", cHeaderPath)
}

func stderr() *os.File {
	return os.Stderr
}
