/* Code generated by cmd/gen-numbers. DO NOT EDIT. */
#ifndef WINESCAPE_NUMBERS_H
#define WINESCAPE_NUMBERS_H

#if defined(__linux__) && (defined(__x86_64__) || defined(_M_X64))
#define WS_SYS_READ 0
#define WS_SYS_WRITE 1
#define WS_SYS_OPEN 2
#define WS_SYS_CLOSE 3
#define WS_SYS_FSTAT 5
#define WS_SYS_LSEEK 8
#define WS_SYS_PREAD64 17
#define WS_SYS_PWRITE64 18
#define WS_SYS_ACCESS 21
#define WS_SYS_GETPID 39
#define WS_SYS_MKDIR 83
#define WS_SYS_RMDIR 84
#define WS_SYS_RENAME 82
#define WS_SYS_UNLINK 87
#define WS_SYS_SYMLINK 88
#define WS_SYS_READLINK 89
#define WS_SYS_GETDENTS64 217
#define WS_SYS_OPENAT 257
#define WS_SYS_MKDIRAT 258
#define WS_SYS_NEWFSTATAT 262
#define WS_SYS_UNLINKAT 263
#define WS_SYS_RENAMEAT 264
#define WS_SYS_READLINKAT 267
#define WS_SYS_FACCESSAT 269
#elif defined(__linux__) && (defined(__aarch64__) || defined(_M_ARM64))
#define WS_SYS_READ 63
#define WS_SYS_WRITE 64
#define WS_SYS_CLOSE 57
#define WS_SYS_FSTAT 80
#define WS_SYS_LSEEK 62
#define WS_SYS_PREAD64 67
#define WS_SYS_PWRITE64 68
#define WS_SYS_GETPID 172
#define WS_SYS_GETDENTS64 61
#define WS_SYS_OPENAT 56
#define WS_SYS_MKDIRAT 34
#define WS_SYS_NEWFSTATAT 79
#define WS_SYS_UNLINKAT 35
#define WS_SYS_RENAMEAT 38
#define WS_SYS_READLINKAT 78
#define WS_SYS_FACCESSAT 48
#elif defined(__FreeBSD__) && (defined(__x86_64__) || defined(_M_X64))
#define WS_SYS_READ 3
#define WS_SYS_WRITE 4
#define WS_SYS_OPEN 5
#define WS_SYS_CLOSE 6
#define WS_SYS_FSTAT 551
#define WS_SYS_LSEEK 478
#define WS_SYS_PREAD64 475
#define WS_SYS_PWRITE64 476
#define WS_SYS_ACCESS 33
#define WS_SYS_GETPID 20
#define WS_SYS_MKDIR 136
#define WS_SYS_RMDIR 137
#define WS_SYS_RENAME 128
#define WS_SYS_UNLINK 10
#define WS_SYS_SYMLINK 57
#define WS_SYS_READLINK 58
#define WS_SYS_GETDIRENTRIES 554
#define WS_SYS_OPENAT 499
#define WS_SYS_MKDIRAT 500
#define WS_SYS_FSTATAT 552
#define WS_SYS_UNLINKAT 503
#define WS_SYS_RENAMEAT 501
#define WS_SYS_READLINKAT 505
#define WS_SYS_FACCESSAT 489
#else
#error "Unsupported host OS / architecture combination for libwinescape"
#endif

#endif /* WINESCAPE_NUMBERS_H */
