package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/unxed/libwinescape/spec"
)

func toCamelCase(snake string) string {
	parts := strings.Split(snake, "_")
	var buf bytes.Buffer
	for _, p := range parts {
		if p == "" {
			continue
		}
		buf.WriteString(strings.ToUpper(p[:1]))
		buf.WriteString(p[1:])
	}
	return buf.String()
}

func generateGoFile(targetOS spec.TargetOS, targetArch spec.TargetArch, buildTag string) string {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-numbers. DO NOT EDIT.\n\n")
	if buildTag != "" {
		buf.WriteString(fmt.Sprintf("//go:build %s\n\n", buildTag))
	}
	buf.WriteString("package winescape\n\n")
	buf.WriteString("const (\n")

	for _, entry := range spec.SyscallTable {
		constName := fmt.Sprintf("sys%s", toCamelCase(entry.Name))
		var num uint64
		if osMap, ok := entry.Numbers[targetOS]; ok {
			if n, ok := osMap[targetArch]; ok {
				num = n
			}
		}
		buf.WriteString(fmt.Sprintf("\t%s uintptr = %d\n", constName, num))
	}

	buf.WriteString(")\n")
	return buf.String()
}

func generateCHeader() string {
	var buf bytes.Buffer
	buf.WriteString("/* Code generated by cmd/gen-numbers. DO NOT EDIT. */\n")
	buf.WriteString("#ifndef WINESCAPE_NUMBERS_H\n")
	buf.WriteString("#define WINESCAPE_NUMBERS_H\n\n")

	targets := []struct {
		os   spec.TargetOS
		arch spec.TargetArch
		cond string
	}{
		{spec.OSLinux, spec.ArchAMD64, "defined(__linux__) && (defined(__x86_64__) || defined(_M_X64))"},
		{spec.OSLinux, spec.ArchARM64, "defined(__linux__) && (defined(__aarch64__) || defined(_M_ARM64))"},
		{spec.OSFreeBSD, spec.ArchAMD64, "defined(__FreeBSD__) && (defined(__x86_64__) || defined(_M_X64))"},
		{spec.OSFreeBSD, spec.ArchARM64, "defined(__FreeBSD__) && (defined(__aarch64__) || defined(_M_ARM64))"},
	}

	for i, t := range targets {
		if i == 0 {
			buf.WriteString(fmt.Sprintf("#if %s\n", t.cond))
		} else {
			buf.WriteString(fmt.Sprintf("#elif %s\n", t.cond))
		}

		for _, entry := range spec.SyscallTable {
			if osMap, ok := entry.Numbers[t.os]; ok {
				if num, ok := osMap[t.arch]; ok {
					macroName := fmt.Sprintf("WS_SYS_%s", strings.ToUpper(entry.Name))
					buf.WriteString(fmt.Sprintf("#define %s %d\n", macroName, num))
				}
			}
		}
	}

	buf.WriteString("#else\n")
	buf.WriteString("#error \"Unsupported host OS / architecture combination for libwinescape\"\n")
	buf.WriteString("#endif\n\n")
	buf.WriteString("#endif /* WINESCAPE_NUMBERS_H */\n")

	return buf.String()
}

func main() {
	rootDir := "."
	if len(os.Args) > 1 {
		rootDir = os.Args[1]
	}

	goFiles := []struct {
		os       spec.TargetOS
		arch     spec.TargetArch
		buildTag string
		path     string
	}{
		{spec.OSLinux, spec.ArchAMD64, "(!winescape_freebsd && windows && amd64) || (linux && amd64)", filepath.Join(rootDir, "go", "numbers_amd64.go")},
		{spec.OSLinux, spec.ArchARM64, "(!winescape_freebsd && windows && arm64) || (linux && arm64)", filepath.Join(rootDir, "go", "numbers_arm64.go")},
		{spec.OSFreeBSD, spec.ArchAMD64, "(winescape_freebsd && windows && amd64) || (freebsd && amd64)", filepath.Join(rootDir, "go", "numbers_freebsd_amd64.go")},
		{spec.OSFreeBSD, spec.ArchARM64, "(winescape_freebsd && windows && arm64) || (freebsd && arm64)", filepath.Join(rootDir, "go", "numbers_freebsd_arm64.go")},
		{"fallback", "fallback", "(!windows && !linux && !freebsd) || (!amd64 && !arm64)", filepath.Join(rootDir, "go", "numbers_fallback.go")},
	}

	for _, gf := range goFiles {
		content := generateGoFile(gf.os, gf.arch, gf.buildTag)
		if err := os.MkdirAll(filepath.Dir(gf.path), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "mkdir error: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(gf.path, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write error for %s: %v\n", gf.path, err)
			os.Exit(1)
		}
		fmt.Printf("Generated %s\n", gf.path)
	}

	cHeaderPath := filepath.Join(rootDir, "c", "include", "winescape_numbers.h")
	if err := os.MkdirAll(filepath.Dir(cHeaderPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir error: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(cHeaderPath, []byte(generateCHeader()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error for %s: %v\n", cHeaderPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", cHeaderPath)
}
