// Code generated by cmd/gen-numbers. DO NOT EDIT.

package winescape

const (
	sysRead uintptr = 63
	sysWrite uintptr = 64
	sysClose uintptr = 57
	sysFstat uintptr = 80
	sysLseek uintptr = 62
	sysPread64 uintptr = 67
	sysPwrite64 uintptr = 68
	sysGetpid uintptr = 172
	sysGetdents64 uintptr = 61
	sysOpenat uintptr = 56
	sysMkdirat uintptr = 34
	sysNewfstatat uintptr = 79
	sysUnlinkat uintptr = 35
	sysRenameat uintptr = 38
	sysReadlinkat uintptr = 78
	sysFaccessat uintptr = 48
)
