// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!windows && !linux && !freebsd) || (!amd64 && !arm64)

package winescape

const (
	sysRead          uintptr = 0
	sysWrite         uintptr = 0
	sysOpen          uintptr = 0
	sysClose         uintptr = 0
	sysFstat         uintptr = 0
	sysLseek         uintptr = 0
	sysPread64       uintptr = 0
	sysPwrite64      uintptr = 0
	sysAccess        uintptr = 0
	sysGetpid        uintptr = 0
	sysMkdir         uintptr = 0
	sysRmdir         uintptr = 0
	sysRename        uintptr = 0
	sysUnlink        uintptr = 0
	sysSymlink       uintptr = 0
	sysReadlink      uintptr = 0
	sysGetdents64    uintptr = 0
	sysGetdirentries uintptr = 0
	sysOpenat        uintptr = 0
	sysMkdirat       uintptr = 0
	sysNewfstatat    uintptr = 0
	sysFstatat       uintptr = 0
	sysUnlinkat      uintptr = 0
	sysRenameat      uintptr = 0
		sysReadlinkat    uintptr = 0
		sysFaccessat     uintptr = 0
		sysPipe2         uintptr = 0
		sysDup3          uintptr = 0
		sysMmap          uintptr = 0
		sysMunmap        uintptr = 0
	)
