// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!winescape_freebsd && windows && arm64) || (linux && arm64)

package winescape

const (
	sysRead          uintptr = 63
	sysWrite         uintptr = 64
	sysOpen          uintptr = 0
	sysClose         uintptr = 57
	sysFstat         uintptr = 80
	sysLseek         uintptr = 62
	sysPread64       uintptr = 67
	sysPwrite64      uintptr = 68
	sysAccess        uintptr = 0
	sysGetpid        uintptr = 172
	sysMkdir         uintptr = 0
	sysRmdir         uintptr = 0
	sysRename        uintptr = 0
	sysUnlink        uintptr = 0
	sysSymlink       uintptr = 0
	sysReadlink      uintptr = 0
	sysGetdents64    uintptr = 61
	sysGetdirentries uintptr = 0
	sysOpenat        uintptr = 56
	sysMkdirat       uintptr = 34
	sysNewfstatat    uintptr = 79
	sysFstatat       uintptr = 0
	sysUnlinkat      uintptr = 35
	sysRenameat      uintptr = 38
	sysReadlinkat    uintptr = 78
	sysFaccessat     uintptr = 48
)
