// Code generated by cmd/gen-numbers. DO NOT EDIT.

package winescape

const (
	sysRead uintptr = 3
	sysWrite uintptr = 4
	sysOpen uintptr = 5
	sysClose uintptr = 6
	sysFstat uintptr = 551
	sysLseek uintptr = 478
	sysPread64 uintptr = 475
	sysPwrite64 uintptr = 476
	sysAccess uintptr = 33
	sysGetpid uintptr = 20
	sysMkdir uintptr = 136
	sysRmdir uintptr = 137
	sysRename uintptr = 128
	sysUnlink uintptr = 10
	sysSymlink uintptr = 57
	sysReadlink uintptr = 58
	sysGetdirentries uintptr = 554
	sysOpenat uintptr = 499
	sysMkdirat uintptr = 500
	sysFstatat uintptr = 552
	sysUnlinkat uintptr = 503
	sysRenameat uintptr = 501
	sysReadlinkat uintptr = 505
	sysFaccessat uintptr = 489
)
