// Code generated by cmd/gen-numbers. DO NOT EDIT.

//go:build (!winescape_freebsd && windows && amd64) || (linux && amd64)

package winescape

const (
	sysRead          uintptr = 0
	sysWrite         uintptr = 1
	sysOpen          uintptr = 2
	sysClose         uintptr = 3
	sysFstat         uintptr = 5
	sysLseek         uintptr = 8
	sysPread64       uintptr = 17
	sysPwrite64      uintptr = 18
	sysAccess        uintptr = 21
	sysGetpid        uintptr = 39
	sysMkdir         uintptr = 83
	sysRmdir         uintptr = 84
	sysRename        uintptr = 82
	sysUnlink        uintptr = 87
	sysSymlink       uintptr = 88
	sysReadlink      uintptr = 89
	sysGetdents64    uintptr = 217
	sysGetdirentries uintptr = 0
	sysOpenat        uintptr = 257
	sysMkdirat       uintptr = 258
	sysNewfstatat    uintptr = 262
	sysFstatat       uintptr = 0
	sysUnlinkat      uintptr = 263
	sysRenameat      uintptr = 264
	sysReadlinkat    uintptr = 267
	sysFaccessat     uintptr = 269
)
